"GET  /":             [ "page.home" ]
"POST /":             [ "submit.home" ]
"GET  /register":     [ "page.register" ]
"POST /register":     [ "submit.register" ]
"GET  /logout":       [ "page.logout" ]
"GET  /games":        [ "mw.guard.login", "page.games" ]
"GET  /games/create": [ "mw.guard.login", "page.games.create" ]
"POST /games/create": [ "mw.guard.login", "submit.games.create" ]